version: "3"

services:
  login_details:
    build:
      context: ./micro_services
      dockerfile: ./Dockerfile
    tty: true
    command: >
      sh -c "python ./manage.py runserver 0.0.0.0:4001"
    ports:
      - "4001:4001"
    volumes:
      - "./micro_services/micro_services:/micro_services"
    depends_on:
      - db

  user_details:
    build:
      context: ./micro_services
      dockerfile: ./Dockerfile
    tty: true
    command: >
      sh -c "python ./manage.py runserver 0.0.0.0:4003"
    ports:
      - "4003:4003"
    volumes:
      - "./micro_services/micro_services:/micro_services"
    depends_on:
      - db

  db:
    image: postgres

  nginx:
    build: ./web
    ports:
      - 80:80
    links:
      - login_details
      - user_details
    depends_on:
      - login_details
      - user_details
