version: "3"

services:
  users:
    build:
      context: ./micro_services
      dockerfile: ./Dockerfile
    tty: true
    command: >
      sh -c "python ./manage.py runserver 0.0.0.0:4001"
    ports:
      - "4001:4001"
    volumes:
      - "./micro_services/micro_services:/micro_services"
    depends_on:
      - db

  jobs:
    build:
      context: ./micro_services
      dockerfile: ./Dockerfile
    tty: true
    command: >
      sh -c "python ./manage.py runserver 0.0.0.0:4002"
    ports:
      - "4002:4002"
    volumes:
      - "./micro_services/micro_services:/micro_services"
    depends_on:
      - db

  roles:
    build:
      context: ./micro_services
      dockerfile: ./Dockerfile
    tty: true
    command: >
      sh -c "python ./manage.py runserver 0.0.0.0:4003"
    ports:
      - "4003:4003"
    volumes:
      - "./micro_services/micro_services:/micro_services"
    depends_on:
      - db
  comments:
    build:
      context: ./micro_services
      dockerfile: ./Dockerfile
    tty: true
    command: >
      sh -c "python ./manage.py runserver 0.0.0.0:4004"
    ports:
      - "4004:4004"
    volumes:
      - "./micro_services/micro_services:/micro_services"
    depends_on:
      - db

  db:
    image: asifsamy/nn-alpine

  nginx:
    build: ./web
    ports:
      - 80:80
    links:
      - users
      - jobs
      - roles
      - comments
    depends_on:
      - users
      - jobs
      - roles
      - comments