# Generated by Django 2.1.9 on 2019-06-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.CharField(max_length=100)),
                ('salary', models.FloatField()),
                ('category', models.CharField(max_length=100)),
                ('address', models.TextField()),
            ],
        ),
    ]
